{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "service-10.fullname" . }}
  labels:
{{- include "service-10.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- toYaml .Values.secret.stringData | nindent 2 }}
{{- end }}
