{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "service-10.serviceAccountName" . }}
  labels:
{{- include "service-10.labels" . | nindent 4 }}
{{- end }}
