apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "service-9.fullname" . }}
  labels:
{{- include "service-9.labels" . | nindent 4 }}
{{- with .Values.commonAnnotations }}
  annotations:
{{- toYaml . | nindent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{- include "service-9.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
{{- include "service-9.selectorLabels" . | nindent 8 }}
{{- with .Values.podLabels }}
{{- toYaml . | nindent 8 }}
{{- end }}
{{- if or .Values.commonAnnotations .Values.podAnnotations }}
      annotations:
{{- with .Values.commonAnnotations }}
{{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.podAnnotations }}
{{- toYaml . | nindent 8 }}
{{- end }}
{{- end }}
    spec:
      serviceAccountName: {{ include "service-9.serviceAccountName" . }}
      containers:
        - name: service-9
          image: "{{ default .Values.global.image.repository .Values.image.repository }}:{{ default .Values.global.image.tag .Values.image.tag }}"
          imagePullPolicy: {{ default .Values.global.image.pullPolicy .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
          env:
{{- if .Values.env }}
{{- toYaml .Values.env | nindent 12 }}
{{- else }}
            []
{{- end }}
{{- if or .Values.config.enabled .Values.secret.enabled }}
          envFrom:
{{- if .Values.config.enabled }}
            - configMapRef:
                name: {{ include "service-9.fullname" . }}
{{- end }}
{{- if .Values.secret.enabled }}
            - secretRef:
                name: {{ include "service-9.fullname" . }}
{{- end }}
{{- end }}
          resources:
{{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
{{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
{{- toYaml .Values.readinessProbe | nindent 12 }}
