{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "service-7.fullname" . }}
  labels:
{{- include "service-7.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
{{- include "service-7.selectorLabels" . | nindent 6 }}
{{- if .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable }}
{{- end }}
{{- if .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
{{- end }}
{{- end }}
